services:

  tomcat:
#    image:  tomcat:8.5.47-jdk8-openjdk
    build:
      context: .
      dockerfile: docker/Tomcat.Dockerfile
    container_name: Tomcat-service
    networks:
      - messenger-demo
    ports:
      - ${TOMCAT_PORT}:8080
    restart: unless-stopped
    deploy:
      mode: replicated
      replicas: ${TOMCAT_REPLICAS}

networks:
  messenger-demo : {}